### ISSUE TITLE
<inherits name='javax.Vecmath' /> in bulletphysics.gwt.xml correct?

### ISSUE THREAD

**Issue by ThomasWrobel** [vbousquet/libgdx-jbullet#1]
Not sure if this project is still developed, and I am probably doing something wrong myself....but anyway.

Trying to use this in a GWT project setup in eclipse.
I added the folder to the project, then added;

```
  <!-- Other module inherits                                      -->
 <inherits name='com.badlogic.gdx'/>
 <inherits name='bulletphysics'/>

```
To my own gwt.xml, as well as adding the gdx jar.

When trying to compile though I get;
   [ERROR] Unable to find 'javax/Vecmath.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

Which is referenced in;
BulletPhysics.gwt.xml

Is that right ? Isnt the point of this project to avoid the user of vecmaths due to licencing? Or is this a different vector maths?

Any pointers would be helpfull,
Cheers,

**Comment by vbousquet** [comment]
You are fully right ; I did not use it in GWT so I did not update the dependencies. The library does not depend on vecmath anymore, so I changed the GWT dependency to point to the LibGdx ones.
